name: Deploy Frontend to Cloudflare Pages

on:
  push:
    paths:
      - 'frontend-app/**'
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd frontend-app
          npm install
          npm run build
          npx next export -o out
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: herwaypoint-frontend
          directory: frontend-app/out
